---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, cloud manager' 
summary: Découvrez les nouveautés de Kubernetes dans BlueXP. 
---
= Nouveautés de Kubernetes dans BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de Kubernetes dans BlueXP (anciennement Cloud Manager).



== 06 novembre 2022

Quand link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["définition des classes de stockage"], vous pouvez maintenant activer l'économie de classe de stockage pour le stockage en mode bloc ou système de fichiers.



== 18 septembre 2022

Vous pouvez désormais importer des clusters OpenShift autogérés dans Cloud Manager.

* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-openshift.html["Conditions requises pour les clusters Kubernetes dans OpenShift"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-add-openshift.html["Ajoutez un cluster OpenShift à Cloud Manager"]




== 31 juillet 2022

* Utilisation du nouveau `- watch` Verbe dans la classe de stockage, la sauvegarde et la restauration des configurations YAML, Cloud Manager peut désormais surveiller les clusters Kubernetes pour les modifications apportées au back-end du cluster et activer automatiquement la sauvegarde des nouveaux volumes persistants si la sauvegarde automatique a été configurée sur le cluster.
+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-aws.html["Conditions requises pour les clusters Kubernetes dans AWS"]

+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-aks.html["Conditions requises pour les clusters Kubernetes dans Azure"]

+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-gke.html["Conditions requises pour les clusters Kubernetes dans Google Cloud"]

* Quand link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["définition des classes de stockage"], vous pouvez maintenant spécifier un type de système de fichiers (fstype) pour le stockage en mode bloc.




== 3 juillet 2022

* Si Astra Trident a été déployé avec l'opérateur Trident, vous pouvez désormais effectuer la mise à niveau vers la dernière version d'Astra Trident avec Cloud Manager.
+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-trident.html["Installer et gérer Astra Trident"]

* Vous pouvez à présent faire glisser votre cluster Kubernetes et le déposer dans l'environnement de travail AWS FSX pour ONTAP afin d'ajouter une classe de stockage directement à partir de la fenêtre Canvas.
+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["Ajouter une classe de stockage"]





== 6 juin 2022

Cloud Manager Suise désormais Amazon FSX pour ONTAP en tant que système de stockage back-end.



== 4 mai 2022



=== Effectuez un glisser-déposer pour ajouter une classe de stockage

Vous pouvez désormais glisser votre cluster Kubernetes et le déposer dans l'environnement de travail Cloud Volumes ONTAP pour ajouter une classe de stockage directement depuis la fenêtre Canvas.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["Ajouter une classe de stockage"]



== 4 avril 2022



=== Gérez des clusters Kubernetes à l'aide de la page de ressources Cloud Manager

La gestion des clusters Kubernetes a maintenant amélioré l'intégration directement depuis l'environnement de travail du cluster. Une nouvelle link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-quick-start.html["Démarrage rapide"] vous permet de vous mettre en route rapidement.

Vous pouvez maintenant effectuer les actions suivantes à partir de la page de ressources du cluster.

* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-trident.html["Installer Astra Trident"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html["Ajouter des classes de stockage"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-persistent-volumes.html["Afficher les volumes persistants"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-remove-cluster.html["Supprimer les clusters"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-kubernetes-enable-services.html["Proposez des services de données"]




== 27 février 2022



=== Prise en charge des clusters Kubernetes dans Google Cloud

Vous pouvez désormais ajouter et gérer des clusters Google Kubernetes Engine (GKE) gérés et des clusters Kubernetes autogérés dans Google Cloud à l'aide de Cloud Manager.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-gke.html["Découvrez comment se lancer avec des clusters Kubernetes dans Google Cloud"].



== 11 janvier 2022



=== Prise en charge des clusters Kubernetes dans Azure

Vous pouvez désormais ajouter et gérer des clusters Azure Kubernetes gérés (AKS) et des clusters Kubernetes autogérés dans Azure à l'aide de Cloud Manager.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-aks.html["Mise en route des clusters Kubernetes dans Azure"]



== 28 novembre 2021



=== Prise en charge des clusters Kubernetes dans AWS

Vous pouvez à présent ajouter vos clusters Kubernetes gérés dans Canvas de Cloud Manager pour une gestion avancée des données.

* Découvrez les clusters Amazon EKS
* Sauvegarde des volumes persistants à l'aide de Cloud Backup


link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html["En savoir plus sur la prise en charge de Kubernetes"].


TIP: Le service Kubernetes existant (disponible via l'onglet *K8s*) est obsolète et sera supprimé dans une prochaine version.
